project_id = "wsckktenxumwmzixbdtv"

[functions.cancel-sync]
verify_jwt = true

[functions.get-meta-config]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-ai-handler]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = true